version: "3.9"

services:
    api:
      build:
        context: .
        target: production
      ports:
        - "3000:3000"
      environment:
        - SECRET=${SECRET}
        - FRONTEND_URL=${FRONTEND_URL}
        - DATABASE_URL=${DATABASE_URL}
        - PORT=3000