version: "3.9"

services:
  api:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL
      - DATABASE_URL
      - REDIS_URL
      - SERVER_PORT
      - SESSION_SECRET
      - NODE_ENV
